name: update application offer

on:
  workflow_dispatch:
    inputs:
      offerId:
        description: 'Offer id'
        required: true
      planId:
        description: 'Plan id'
        required: true
      filePath:
        description: 'Artifact file path'
        required: true
      artifactVersion:
        description: 'Artifact version'
        required: true
        default: '1.0.0'

env:
    offerId: ${{ github.event.inputs.offerId }}
    planId: ${{ github.event.inputs.planId }}
    filePath: ${{ github.event.inputs.filePath }}
    artifactVersion: ${{ github.event.inputs.artifactVersion }}
    clientId: ${{ secrets.CLIENT_ID }}
    secretValue: ${{ secrets.SECRET_VALUE }}
    tenantId: ${{ secrets.TENANT_ID }}
    offerType: 'application_offer'

jobs:
  update_artifact_job:
    runs-on: ubuntu-latest
    name: A job to update Partner Center application offer artifact
    steps:
      - name: Update offer artifact
        id: update-offer-artifact
        uses: microsoft/microsoft-partner-center-github-action@v3.2
        with:
          offerId: ${{ env.offerId }}
          planId: ${{ env.planId }}
          offerType: ${{ env.offerType }}
          filePath: ${{ env.filePath }}
          artifactVersion: ${{ env.artifactVersion }}
          clientId: ${{ env.clientId }}
          secretValue: ${{ env.secretValue }}
          tenantId: ${{ env.tenantId }}
          verbose: "true"
